apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hw87eo8dt-python
  janus-idp.io/tekton: hw87eo8dt-python
  backstage.io/kubernetes-id: hw87eo8dt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw87eo8dt-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
