apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hw87eo8dt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hw87eo8dt-python 
  name: hw87eo8dt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hw87eo8dt-python 
